package com.mybatis.client;

import com.mybatis.java.Activities;
import com.mybatis.java.ActivitiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int countByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int deleteByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int insert(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int insertSelective(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    List<Activities> selectByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    Activities selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") Activities record, @Param("example") ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int updateByExample(@Param("record") Activities record, @Param("example") ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int updateByPrimaryKeySelective(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    int updateByPrimaryKey(Activities record);
}