package com.mybatis.java;

import java.util.Date;

public class Activities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.id
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.title
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.type_enum
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String typeEnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.scenic_spots
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String scenicSpots;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.departure
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String departure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.destination
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.leader
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.start_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activities.end_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.id
     *
     * @return the value of activities.id
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.id
     *
     * @param id the value for activities.id
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.title
     *
     * @return the value of activities.title
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.title
     *
     * @param title the value for activities.title
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.type_enum
     *
     * @return the value of activities.type_enum
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getTypeEnum() {
        return typeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.type_enum
     *
     * @param typeEnum the value for activities.type_enum
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setTypeEnum(String typeEnum) {
        this.typeEnum = typeEnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.scenic_spots
     *
     * @return the value of activities.scenic_spots
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getScenicSpots() {
        return scenicSpots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.scenic_spots
     *
     * @param scenicSpots the value for activities.scenic_spots
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setScenicSpots(String scenicSpots) {
        this.scenicSpots = scenicSpots;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.departure
     *
     * @return the value of activities.departure
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.departure
     *
     * @param departure the value for activities.departure
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setDeparture(String departure) {
        this.departure = departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.destination
     *
     * @return the value of activities.destination
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.destination
     *
     * @param destination the value for activities.destination
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.leader
     *
     * @return the value of activities.leader
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.leader
     *
     * @param leader the value for activities.leader
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setLeader(String leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.start_date
     *
     * @return the value of activities.start_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.start_date
     *
     * @param startDate the value for activities.start_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activities.end_date
     *
     * @return the value of activities.end_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activities.end_date
     *
     * @param endDate the value for activities.end_date
     *
     * @mbggenerated Wed Jun 11 14:58:28 CST 2014
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}